/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governatorContractSol from "./GovernatorContract.sol";
export { TimeLock__factory } from "./TimeLock__factory";
