/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governatorContractSol from "./GovernatorContract.sol";
export type { governatorContractSol };
export type { TimeLock } from "./TimeLock";
